defaults:
  - train
  - _self_

q: 500
N: 2000
idx_t0: 10
idx_t1: 90
discrete: True

alpha: 0.01

time_domain:
  _target_: pinnstf2.data.TimeDomain
  t_interval: [0, 1]
  t_points: 1000

spatial_domain:
  _target_: pinnstf2.data.Interval
  x_interval: [0, 1]
  shape: [200, 1]

mesh:
  _target_: pinnstf2.data.Mesh
  root_dir: ${paths.data_dir}
  read_data_fn: ???
  ub: [1.0, 1.0]
  lb: [0.0, 0.0]

runge_kutta:
  _target_: pinnstf2.models.RungeKutta
  root_dir: ${paths.rk_dir}
  q: ${q}
  t1: ${idx_t0}
  t2: ${idx_t1}
  time_domain: ${time_domain}

train_datasets:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      num_sample: ${N}
      solution:
        - u
      collection_points:
        - f

val_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

pred_dataset:
  - mesh_sampler:
      _target_: pinnstf2.data.MeshSampler
      _partial_: true
      idx_t: ${idx_t1}
      solution:
        - u

net:
  _target_: pinnstf2.models.FCN
  layers:
    - 1
    - 50
    - 50
    - 50
    - ${eval:'${q} + 1'}
  output_names:
    - u
  discrete: ${discrete}

trainer:
  max_epochs: 10000
  check_val_every_n_epoch: 1000

model:
  loss_fn: sse
  runge_kutta: ${runge_kutta}

train: true
test: false
val: true
optimized_metric:
  error:
    - u

plotting:
  # _target_: pinnstf2.utils.plot_burgers_discrete_forward
  _target_: pinnstf2.utils.plot_ac
  _partial_: true

seed: 1234
task_name: burgers_discrete_forward

hydra:
  searchpath:
    - pkg://pinnstf2/conf